spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver   # ???? MySQL ???
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: 123456
mybatis:
  configuration:
    map-underscore-to-camel-case: true  #驼峰命名，下划线命名相互转换
    mapper-locations: classpath:mapper/*.xml  # ???????
    type-aliases-package: com.example.my_project.entity  # ??????
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  hikari:
    maximum-pool-size: 10  # ???????
    minimum-idle: 5         # ???????
    idle-timeout: 30000     # ????????????
    max-lifetime: 600000    # ????????????
    connection-timeout: 30000 # ????????????
    pool-name: HikariCP      # ?????
debug: true
#??
server:
  port: 9090
